### ISSUE TITLE
Ndless installed still shown

### ISSUE THREAD

**Issue by friedensfurz** [Decimation/HideCAS#4]
Hey man, thank you for your great work. For me, some things are different to your guide:

When I install Ndless, the CAS logo is hidden, but the green text still says "Ndless installed!". However, that is the exact same in exam mode, cas is also not shown. Can you help me out? Cheers

**Comment by Decimation** [comment]
Did you replace your `ndless_resources.tns`?

**Comment by friedensfurz** [comment]
Yes! First my steps:
1. (Install the CAS Rom on CX Version)
2. create ndless folder
3. Put ndless and installer and your ndless_resource in it
4. Run installer and reboot

Results are as follows:
"ndless_resources.tns" from your page: CAS logo gone, but still the full "Ndless installed!" text
"ndless_resources_nohide" from your page: CAS logo and "Ndless installed!" shown.

I'm really confused because I have no idea where ndless is gathering the original string from.
Could that be in the ndless installer? 
Thanks

**Comment by Decimation** [comment]
It appears I misnamed the files. Try again and let me know what happens.

**Comment by friedensfurz** [comment]
Solved. New file works. Thank you for the quick fix :-))
